services:
  caddy:
    image: "caddy:latest"
    container_name: caddy
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./caddy_data:/data
        - ./caddy_config:/config
    environment:
        - ACME_AGREE=true
     
  backend:
    image: "hackduke/blueride-core:1.0.1"
    environment:
      SENTRY_LINK: ${BC_SENTRY_LINK}
      MONGO_URL: ${BC_MONGO_URL}
      AMQP_URI: ${BC_AMQP_URI}
      SECRET: ${BC_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "9999:8080"
    restart: on-failure:3

  mailer:
    image: "hackduke/blueride-mailer:latest"
    environment:
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SENTRY_DSN: ${SENTRY_DSN}
      RABBITMQ_URI: ${RABBITMQ_URI}
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure:3
  rabbitmq:
    image: "rabbitmq:3.13.0-alpine"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
      start_period: 30s
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf # Mount custom configuration file
      - rabbitmq-data:/var/lib/rabbitmq/
    restart: on-failure:3

volumes:
  rabbitmq-data:
