apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hackduke/blueride-core:1.0.1
        env:
        - name: SENTRY_LINK
          value: ${BC_SENTRY_LINK}
        - name: MONGO_URL
          value: ${BC_MONGO_URL}
        - name: AMQP_URI
          value: ${BC_AMQP_URI}
        - name: SECRET
          value: ${BC_SECRET}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 90
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
      - name: mailer
        image: hackduke/blueride-mailer:latest
        env:
        - name: SMTP_USERNAME
          value: ${SMTP_USERNAME}
        - name: SMTP_PASSWORD
          value: ${SMTP_PASSWORD}
        - name: SMTP_HOST
          value: ${SMTP_HOST}
        - name: SENTRY_DSN
          value: ${SENTRY_DSN}
        - name: RABBITMQ_URI
          value: ${RABBITMQ_URI}
---
apiVersion: v1
kind: Service
metadata:
  name: mailer
spec:
  selector:
    app: mailer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.13.0-alpine
        volumeMounts:
        - name: rabbitmq-conf
          mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq/
        livenessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 20
      volumes:
      - name: rabbitmq-conf
        configMap:
          name: rabbitmq-conf
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-conf
data:
  rabbitmq.conf: |-
    listeners.tcp.1 = :::5672
    default_user = blueride
    default_pass = placeholder
